- debug:
    var: Bastion

- name: Update apt repositories
  ansible.builtin.apt:
    update_cache: true
    force_apt_get: true
    cache_valid_time: 86400

- name: Install sudo
  ansible.builtin.apt:
    name: sudo
    update_cache: true

- name: Make sure we have a 'sudo' group
  group:
    name: sudo
    state: present

- name: "Add group '{{ ansible_user_group_name }}'"
  group:
    name: "{{ ansible_user_group_name }}"
    gid: "{{ ansible_user_group_id }}"
    state: present

- name: "Add the user '{{ ansible_user_user_name }}'"
  ansible.builtin.user:
    name: "{{ ansible_user_user_name }}"
    comment: Ansible user
    uid: "{{ ansible_user_user_id }}"
    group: "{{ ansible_user_group_name }}"
    groups: sudo
    append: true
    shell: /bin/bash
    create_home: true
    home: "{{ ansible_user_user_home }}"

- name: Create .ssh directory
  ansible.builtin.file:
    path: "{{ ansible_user_user_home }}/.ssh"
    state: directory
    owner: "{{ ansible_user_user_name }}"
    group: "{{ ansible_user_group_name }}"
    mode: '0700'

- name: "Set authorized key for '{{ ansible_user_user_name }}' user"
  ansible.posix.authorized_key:
    user: "{{ ansible_user_user_name }}"
    state: present
    key: "{{ lookup('file', 'vaults/bastion_public_keys.yml') }}"
    exclusive: true
  when: Bastion|default(false)|bool == true

- name: Copy ssh private key
  ansible.builtin.copy:
    src: files/.ssh/id_ed25519
    dest: "{{ ansible_user_user_home }}/.ssh/id_ed25519"
    owner: "{{ ansible_user_user_name }}"
    group: "{{ ansible_user_group_name }}"
    mode: '0600'
  when: Bastion|default(false)|bool == true

- name: Set authorized key taken from file
  ansible.posix.authorized_key:
    user: "{{ ansible_user_user_name }}"
    state: present
    key: "{{ lookup('file', '../ansible/.ssh/id_ed25519.pub') }}"

- name: "Allow {{ ansible_user_user_name }} user to have passwordless sudo"
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%{{ ansible_user_user_name }}"
    line: "%{{ ansible_user_user_name }} ALL=(ALL:ALL) NOPASSWD: ALL"
    validate: visudo -cf %s
